/* eslint-disable import/extensions */
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Navbar from "@/components/Navbar.tsx/Navbar";
import { Suspense } from "react";
import TransitionSuspense from "@/components/TransitionLayer.tsx/TransitionSuspense";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en" className="overflow-x-hidden">
    <body className={`overflow-x-hidden ${inter.className}`}>
      <Suspense fallback={<TransitionSuspense />}>
        <Navbar />
        {children}
      </Suspense>
    </body>
  </html>
);

export default RootLayout;
